// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWQC4XVR46_KbR32N-YY_SyvPJAfZ35c',
    appId: '1:58268129544:web:568bf080f32880993934bd',
    messagingSenderId: '58268129544',
    projectId: 'vicoba-c89a7',
    authDomain: 'vicoba-c89a7.firebaseapp.com',
    databaseURL: 'https://vicoba-c89a7-default-rtdb.firebaseio.com',
    storageBucket: 'vicoba-c89a7.firebasestorage.app',
    measurementId: 'G-B900R4NFGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BbnN6qy1D57zEMV4We9D6UZ1YTftWtU',
    appId: '1:58268129544:android:b1b1810a51144cdf3934bd',
    messagingSenderId: '58268129544',
    projectId: 'vicoba-c89a7',
    databaseURL: 'https://vicoba-c89a7-default-rtdb.firebaseio.com',
    storageBucket: 'vicoba-c89a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXUdMh_Rpadc9ZD6PuQZIW-lschrnUBq4',
    appId: '1:58268129544:ios:46e3398fb17dcca23934bd',
    messagingSenderId: '58268129544',
    projectId: 'vicoba-c89a7',
    databaseURL: 'https://vicoba-c89a7-default-rtdb.firebaseio.com',
    storageBucket: 'vicoba-c89a7.firebasestorage.app',
    iosBundleId: 'tz.co.zima.vicoba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXUdMh_Rpadc9ZD6PuQZIW-lschrnUBq4',
    appId: '1:58268129544:ios:46e3398fb17dcca23934bd',
    messagingSenderId: '58268129544',
    projectId: 'vicoba-c89a7',
    databaseURL: 'https://vicoba-c89a7-default-rtdb.firebaseio.com',
    storageBucket: 'vicoba-c89a7.firebasestorage.app',
    iosBundleId: 'tz.co.zima.vicoba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWQC4XVR46_KbR32N-YY_SyvPJAfZ35c',
    appId: '1:58268129544:web:8e6e421c908f88a83934bd',
    messagingSenderId: '58268129544',
    projectId: 'vicoba-c89a7',
    authDomain: 'vicoba-c89a7.firebaseapp.com',
    databaseURL: 'https://vicoba-c89a7-default-rtdb.firebaseio.com',
    storageBucket: 'vicoba-c89a7.firebasestorage.app',
    measurementId: 'G-5JF3DEV7SJ',
  );
}
