// File generated by FlutterFire CLI. Project: tajiri-6d6ae.
// Firebase initializes in main.dart; LiveUpdateService listens to Firestore updates/{userId} for instant UI refresh.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZN_wBWIaQdvJrslk2tB-5aHU8JILZJlA',
    appId: '1:281691609201:web:093295e6c47198a0e7e3d0',
    messagingSenderId: '281691609201',
    projectId: 'tajiri-6d6ae',
    authDomain: 'tajiri-6d6ae.firebaseapp.com',
    storageBucket: 'tajiri-6d6ae.firebasestorage.app',
    measurementId: 'G-MZHEPF50QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xEbMQgJgAxPDNPP77yC7Tiraj7FawfQ',
    appId: '1:281691609201:android:5fdbc252113fc11ae7e3d0',
    messagingSenderId: '281691609201',
    projectId: 'tajiri-6d6ae',
    storageBucket: 'tajiri-6d6ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcVTMJOL4SJW-3tJyA62DrgY-B6fxguOE',
    appId: '1:281691609201:ios:5cada4db0cfb2bf3e7e3d0',
    messagingSenderId: '281691609201',
    projectId: 'tajiri-6d6ae',
    storageBucket: 'tajiri-6d6ae.firebasestorage.app',
    iosBundleId: 'tz.co.zima.tajiri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcVTMJOL4SJW-3tJyA62DrgY-B6fxguOE',
    appId: '1:281691609201:ios:5cada4db0cfb2bf3e7e3d0',
    messagingSenderId: '281691609201',
    projectId: 'tajiri-6d6ae',
    storageBucket: 'tajiri-6d6ae.firebasestorage.app',
    iosBundleId: 'tz.co.zima.tajiri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZN_wBWIaQdvJrslk2tB-5aHU8JILZJlA',
    appId: '1:281691609201:web:301446c8b273a3d5e7e3d0',
    messagingSenderId: '281691609201',
    projectId: 'tajiri-6d6ae',
    authDomain: 'tajiri-6d6ae.firebaseapp.com',
    storageBucket: 'tajiri-6d6ae.firebasestorage.app',
    measurementId: 'G-799HYJ4VRB',
  );

}