// lib/payroll/pages/payslip_page.dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import '../../l10n/app_strings_scope.dart';
import '../models/payroll_models.dart';

const Color _kPrimary = Color(0xFF1A1A1A);
const Color _kSecondary = Color(0xFF666666);
const Color _kBg = Color(0xFFFAFAFA);
const Color _kCard = Color(0xFFFFFFFF);

class PayslipPage extends StatelessWidget {
  final PayrollEntry entry;
  final int month;
  final int year;
  final String businessName;

  const PayslipPage({
    super.key,
    required this.entry,
    required this.month,
    required this.year,
    this.businessName = '',
  });

  static const _monthsEn = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];

  static const _monthsSw = [
    'Januari', 'Februari', 'Machi', 'Aprili', 'Mei', 'Juni',
    'Julai', 'Agosti', 'Septemba', 'Oktoba', 'Novemba', 'Desemba',
  ];

  void _share(bool sw) {
    final nf = NumberFormat('#,###', 'en');
    final monthName = sw ? _monthsSw[month - 1] : _monthsEn[month - 1];
    final displayBusiness = businessName.isNotEmpty ? businessName : (sw ? 'Biashara Yako' : 'Your Business');
    const sep = '─────────────────────────────';
    final buf = StringBuffer();
    buf.writeln(sep);
    buf.writeln('${sw ? "STAKABADHI YA MSHAHARA" : "PAYSLIP"} — $monthName $year');
    buf.writeln(displayBusiness);
    buf.writeln('${sw ? "Mfanyakazi" : "Employee"}: ${entry.employeeName}');
    buf.writeln(sep);
    buf.writeln(sw ? 'MAPATO' : 'EARNINGS');
    buf.writeln('${sw ? "Mshahara Msingi" : "Basic Salary"}:       TZS ${nf.format(entry.grossSalary)}');
    buf.writeln(sep);
    buf.writeln(sw ? 'MAKATO' : 'DEDUCTIONS');
    buf.writeln('PAYE:              -TZS ${nf.format(entry.paye)}');
    buf.writeln('${sw ? "NSSF (Mfanyakazi)" : "NSSF (Employee)"}:   -TZS ${nf.format(entry.nssfEmployee)}');
    buf.writeln(sep);
    buf.writeln('${sw ? "MSHAHARA HALISI" : "NET PAY"}:            TZS ${nf.format(entry.netSalary)}');
    buf.writeln(sep);
    buf.writeln(sw ? 'Mwajiri pia analipa:' : 'Employer also pays:');
    buf.writeln('${sw ? "NSSF (Mwajiri)" : "NSSF (Employer)"}:    TZS ${nf.format(entry.nssfEmployer)}');
    buf.writeln('SDL:                TZS ${nf.format(entry.sdl)}');
    buf.writeln('WCF:                TZS ${nf.format(entry.wcf)}');
    buf.writeln('${sw ? "Jumla Gharama" : "Total cost to employer"}: TZS ${nf.format(entry.totalEmployerCost)}');
    buf.writeln(sep);
    buf.write(sw ? 'Imetolewa na TAJIRI Payroll' : 'Generated by TAJIRI Payroll');
    Share.share(buf.toString());
  }

  @override
  Widget build(BuildContext context) {
    final sw = AppStringsScope.of(context)?.isSwahili ?? false;
    final nf = NumberFormat('#,###', 'en');
    final monthName = sw ? _monthsSw[month - 1] : _monthsEn[month - 1];

    return Scaffold(
      backgroundColor: _kBg,
      appBar: AppBar(
        backgroundColor: _kBg,
        elevation: 0,
        leading: const BackButton(color: _kPrimary),
        title: Text(
          sw ? 'Stakabadhi ya Mshahara' : 'Payslip',
          style: const TextStyle(color: _kPrimary, fontWeight: FontWeight.w600),
        ),
      ),
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            // Header card
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: _kPrimary,
                borderRadius: BorderRadius.circular(16),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                      businessName.isNotEmpty
                          ? businessName
                          : (sw ? 'Biashara Yako' : 'Your Business'),
                      style: const TextStyle(
                          color: Colors.white70, fontSize: 12),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis),
                  Text(
                    sw ? 'STAKABADHI YA MSHAHARA' : 'PAYSLIP',
                    style: const TextStyle(
                        color: Colors.white,
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 1.2),
                  ),
                  Text('$monthName $year',
                      style: const TextStyle(color: Colors.white70, fontSize: 13)),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      CircleAvatar(
                        radius: 20,
                        backgroundColor: Colors.white.withValues(alpha: 0.15),
                        child: Text(
                          entry.employeeName.isNotEmpty
                              ? entry.employeeName[0].toUpperCase()
                              : '?',
                          style: const TextStyle(
                              color: Colors.white,
                              fontWeight: FontWeight.bold,
                              fontSize: 16),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          entry.employeeName,
                          style: const TextStyle(
                              color: Colors.white,
                              fontWeight: FontWeight.w600,
                              fontSize: 15),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            const SizedBox(height: 16),

            // Earnings card
            _sectionCard(
              title: sw ? 'Mapato' : 'Earnings',
              children: [
                _row(sw ? 'Mshahara Msingi' : 'Basic Salary',
                    nf.format(entry.grossSalary)),
                const Divider(height: 12),
                _row(sw ? 'Jumla Mapato' : 'Total Earnings',
                    nf.format(entry.grossSalary),
                    isBold: true),
              ],
            ),

            const SizedBox(height: 10),

            // Deductions card
            _sectionCard(
              title: sw ? 'Makato' : 'Deductions',
              children: [
                _row('PAYE', nf.format(entry.paye),
                    valueColor: Colors.red.shade700),
                _row(sw ? 'NSSF (Mfanyakazi 10%)' : 'NSSF (Employee 10%)',
                    nf.format(entry.nssfEmployee),
                    valueColor: Colors.red.shade700),
                const Divider(height: 12),
                _row(sw ? 'Jumla Makato' : 'Total Deductions',
                    nf.format(entry.paye + entry.nssfEmployee),
                    isBold: true),
              ],
            ),

            const SizedBox(height: 16),

            // Net pay hero
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: _kPrimary,
                borderRadius: BorderRadius.circular(16),
              ),
              child: Column(
                children: [
                  Text(
                    sw ? 'Mshahara Halisi' : 'Net Pay',
                    style: const TextStyle(color: Colors.white70, fontSize: 13),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'TZS ${nf.format(entry.netSalary)}',
                    style: const TextStyle(
                        color: Colors.white,
                        fontSize: 28,
                        fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 10),

            // Employer costs footnote
            Container(
              padding: const EdgeInsets.all(14),
              decoration: BoxDecoration(
                color: _kCard,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.grey.shade100),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    sw ? 'Gharama za Mwajiri' : 'Employer Costs',
                    style: const TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: _kPrimary),
                  ),
                  const SizedBox(height: 6),
                  _row(sw ? 'NSSF (Mwajiri 10%)' : 'NSSF (Employer 10%)',
                      nf.format(entry.nssfEmployer)),
                  _row('SDL (3.5%)', nf.format(entry.sdl)),
                  _row('WCF (0.5%)', nf.format(entry.wcf)),
                  const Divider(height: 10),
                  _row(sw ? 'Jumla Gharama' : 'Total Employer Cost',
                      nf.format(entry.totalEmployerCost),
                      isBold: true),
                ],
              ),
            ),

            const SizedBox(height: 16),

            // Share button
            SizedBox(
              width: double.infinity,
              height: 46,
              child: OutlinedButton.icon(
                onPressed: () => _share(sw),
                icon: const Icon(Icons.share_rounded, size: 18),
                label: Text(
                  sw ? 'Shiriki Stakabadhi' : 'Share Payslip',
                  style: const TextStyle(
                      fontSize: 14, fontWeight: FontWeight.w600),
                ),
                style: OutlinedButton.styleFrom(
                  foregroundColor: _kPrimary,
                  side: const BorderSide(color: _kPrimary),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12)),
                ),
              ),
            ),

            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _sectionCard(
      {required String title, required List<Widget> children}) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _kCard,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.shade100),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title,
              style: const TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  color: _kPrimary)),
          const SizedBox(height: 8),
          ...children,
        ],
      ),
    );
  }

  Widget _row(String label, String value,
      {bool isBold = false, Color? valueColor}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Flexible(
            child: Text(
              label,
              style: TextStyle(
                  fontSize: 12,
                  color: _kSecondary,
                  fontWeight:
                      isBold ? FontWeight.w600 : FontWeight.normal),
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          const SizedBox(width: 8),
          Text(
            'TZS $value',
            style: TextStyle(
                fontSize: 12,
                color: valueColor ?? _kPrimary,
                fontWeight: isBold ? FontWeight.bold : FontWeight.w500),
          ),
        ],
      ),
    );
  }
}
