#!/usr/bin/env bash
# RFQ API smoke/integration tester for TAJIRI backend.
#
# Usage examples:
#   ./scripts/test_rfq_api.sh sent
#   ./scripts/test_rfq_api.sh received
#   ./scripts/test_rfq_api.sh detail 12
#   ./scripts/test_rfq_api.sh responses 12
#   ./scripts/test_rfq_api.sh create
#   ./scripts/test_rfq_api.sh respond 12
#   ./scripts/test_rfq_api.sh accept 12 44
#   ./scripts/test_rfq_api.sh reject 12 45
#   ./scripts/test_rfq_api.sh smoke
#
# Required env vars:
#   BASE_URL               default: https://tajiri.zimasystems.com/api
#   BUYER_TOKEN            bearer token for requester-side actions
#   SUPPLIER_TOKEN         bearer token for supplier-side actions
#   REQUESTER_BUSINESS_ID  default: 1
#   DESTINATION_BUSINESS_ID default: 2
#   REQUESTER_USER_ID      default: 31
#   RESPONDER_USER_ID      default: 32
#   RFQ_ID                 optional fallback for detail/respond/responses/accept/reject
#   RESPONSE_ID            optional fallback for accept/reject

set -euo pipefail

BASE_URL="${BASE_URL:-https://tajiri.zimasystems.com/api}"
REQUESTER_BUSINESS_ID="${REQUESTER_BUSINESS_ID:-1}"
DESTINATION_BUSINESS_ID="${DESTINATION_BUSINESS_ID:-2}"
REQUESTER_USER_ID="${REQUESTER_USER_ID:-31}"
RESPONDER_USER_ID="${RESPONDER_USER_ID:-32}"
BUYER_TOKEN="${BUYER_TOKEN:-}"
SUPPLIER_TOKEN="${SUPPLIER_TOKEN:-}"
command -v curl >/dev/null 2>&1 || { echo "curl is required"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "python3 is required"; exit 1; }

ACTION="${1:-smoke}"
ARG_RfqId="${2:-}"
ARG_ResponseId="${3:-}"

json_extract() {
  local expr="$1"
  python3 -c "import json,sys; data=json.load(sys.stdin); value=$expr; print('' if value is None else value)"
}

pretty_print() {
  python3 -m json.tool 2>/dev/null || cat
}

call_api() {
  local method="$1"
  local token="$2"
  local path="$3"
  local body="${4:-}"
  local url="${BASE_URL}${path}"

  if [[ -n "$body" ]]; then
    curl -sS -X "$method" "$url" \
      -H "Accept: application/json" \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $token" \
      -d "$body"
  else
    curl -sS -X "$method" "$url" \
      -H "Accept: application/json" \
      -H "Authorization: Bearer $token"
  fi
}

require_token() {
  local token="$1"
  local label="$2"
  if [[ -z "$token" ]]; then
    echo "$label is required for this action."
    exit 1
  fi
}

resolve_rfq_id() {
  if [[ -n "$ARG_RfqId" ]]; then
    printf "%s" "$ARG_RfqId"
  elif [[ -n "${RFQ_ID:-}" ]]; then
    printf "%s" "${RFQ_ID}"
  else
    echo ""
  fi
}

resolve_response_id() {
  if [[ -n "$ARG_ResponseId" ]]; then
    printf "%s" "$ARG_ResponseId"
  elif [[ -n "${RESPONSE_ID:-}" ]]; then
    printf "%s" "${RESPONSE_ID}"
  else
    echo ""
  fi
}

create_rfq() {
  require_token "$BUYER_TOKEN" "BUYER_TOKEN"
  local payload
  payload="$(python3 - <<PY
import json, uuid
print(json.dumps({
  "requester_business_id": int("${REQUESTER_BUSINESS_ID}"),
  "recipient_business_ids": [int("${DESTINATION_BUSINESS_ID}")],
  "currency": "TZS",
  "source_mode": "catalog_match",
  "needed_by": "2026-04-30T00:00:00Z",
  "response_deadline": "2026-04-25T17:00:00Z",
  "requirements": "API smoke test RFQ from Cursor",
  "notes": f"cursor-rfq-test::{uuid.uuid4()}",
  "items": [
    {
      "item_type": "custom",
      "title": "API Smoke Test Item",
      "description": "Generated by scripts/test_rfq_api.sh",
      "quantity": 2
    }
  ]
}))
PY
)"
  call_api "POST" "$BUYER_TOKEN" "/business/rfq" "$payload"
}

list_sent() {
  require_token "$BUYER_TOKEN" "BUYER_TOKEN"
  call_api "GET" "$BUYER_TOKEN" "/business/rfq/sent?requester_business_id=${REQUESTER_BUSINESS_ID}"
}

list_received() {
  require_token "$SUPPLIER_TOKEN" "SUPPLIER_TOKEN"
  call_api "GET" "$SUPPLIER_TOKEN" "/business/rfq/received?destination_business_id=${DESTINATION_BUSINESS_ID}"
}

rfq_detail() {
  require_token "$BUYER_TOKEN" "BUYER_TOKEN"
  local rfq_id
  rfq_id="$(resolve_rfq_id)"
  [[ -n "$rfq_id" ]] || { echo "RFQ ID required"; exit 1; }
  call_api "GET" "$BUYER_TOKEN" "/business/rfq/${rfq_id}"
}

mark_viewed() {
  require_token "$SUPPLIER_TOKEN" "SUPPLIER_TOKEN"
  local rfq_id
  rfq_id="$(resolve_rfq_id)"
  [[ -n "$rfq_id" ]] || { echo "RFQ ID required"; exit 1; }
  call_api "PATCH" "$SUPPLIER_TOKEN" "/business/rfq/${rfq_id}/viewed"
}

respond_rfq() {
  require_token "$SUPPLIER_TOKEN" "SUPPLIER_TOKEN"
  local rfq_id
  rfq_id="$(resolve_rfq_id)"
  [[ -n "$rfq_id" ]] || { echo "RFQ ID required"; exit 1; }
  local payload
  payload="$(python3 - <<PY
import json, uuid
print(json.dumps({
  "responder_business_id": int("${DESTINATION_BUSINESS_ID}"),
  "responder_user_id": int("${RESPONDER_USER_ID}"),
  "currency": "TZS",
  "subtotal": 50000,
  "vat_rate": 18,
  "vat_amount": 9000,
  "total_amount": 59000,
  "lead_time": "3 days",
  "validity": "Valid for 7 days",
  "terms": "Supplier smoke test terms",
  "notes": f"cursor-rfq-response::{uuid.uuid4()}",
  "items": [
    {
      "title": "API Smoke Test Item",
      "quantity": 2,
      "unit_price": 25000,
      "total_price": 50000
    }
  ]
}))
PY
)"
  call_api "POST" "$SUPPLIER_TOKEN" "/business/rfq/${rfq_id}/respond" "$payload"
}

list_responses() {
  require_token "$BUYER_TOKEN" "BUYER_TOKEN"
  local rfq_id
  rfq_id="$(resolve_rfq_id)"
  [[ -n "$rfq_id" ]] || { echo "RFQ ID required"; exit 1; }
  call_api "GET" "$BUYER_TOKEN" "/business/rfq/${rfq_id}/responses"
}

extract_first_response_id_from_detail() {
  local rfq_id detail_json
  rfq_id="$1"
  detail_json="$(RFQ_ID="$rfq_id" rfq_detail)"
  echo "$detail_json" | json_extract "data['data']['responses'][0]['id'] if isinstance(data, dict) and 'data' in data and isinstance(data['data'], dict) and isinstance(data['data'].get('responses'), list) and data['data']['responses'] else ''"
}

accept_response() {
  require_token "$BUYER_TOKEN" "BUYER_TOKEN"
  local rfq_id response_id payload
  rfq_id="$(resolve_rfq_id)"
  response_id="$(resolve_response_id)"
  [[ -n "$rfq_id" ]] || { echo "RFQ ID required"; exit 1; }
  [[ -n "$response_id" ]] || { echo "Response ID required"; exit 1; }
  payload="{\"response_id\": ${response_id}, \"close_others\": true, \"requester_business_id\": ${REQUESTER_BUSINESS_ID}}"
  call_api "PATCH" "$BUYER_TOKEN" "/business/rfq/${rfq_id}/accept" "$payload"
}

reject_response() {
  require_token "$BUYER_TOKEN" "BUYER_TOKEN"
  local rfq_id response_id payload
  rfq_id="$(resolve_rfq_id)"
  response_id="$(resolve_response_id)"
  [[ -n "$rfq_id" ]] || { echo "RFQ ID required"; exit 1; }
  [[ -n "$response_id" ]] || { echo "Response ID required"; exit 1; }
  payload="{\"response_id\": ${response_id}, \"requester_business_id\": ${REQUESTER_BUSINESS_ID}}"
  call_api "PATCH" "$BUYER_TOKEN" "/business/rfq/${rfq_id}/reject" "$payload"
}

smoke_test() {
  echo "=== RFQ CREATE ==="
  local create_json
  create_json="$(create_rfq)"
  echo "$create_json" | pretty_print
  local rfq_id
  rfq_id="$(echo "$create_json" | json_extract "data['data']['threads'][0]['id'] if isinstance(data, dict) and 'data' in data and isinstance(data['data'], dict) and isinstance(data['data'].get('threads'), list) and data['data']['threads'] else ''")"
  if [[ -z "$rfq_id" ]]; then
    echo "Unable to extract RFQ ID from create response."
    exit 1
  fi

  echo ""
  echo "=== RFQ SENT INBOX ==="
  list_sent | pretty_print

  echo ""
  echo "=== RFQ RECEIVED INBOX ==="
  list_received | pretty_print

  echo ""
  echo "=== RFQ DETAIL ==="
  RFQ_ID="$rfq_id" rfq_detail | pretty_print

  echo ""
  echo "=== RFQ MARK VIEWED ==="
  RFQ_ID="$rfq_id" mark_viewed | pretty_print

  echo ""
  echo "=== RFQ RESPOND ==="
  local respond_json
  respond_json="$(RFQ_ID="$rfq_id" respond_rfq)"
  echo "$respond_json" | pretty_print

  echo ""
  echo "=== RFQ RESPONSES ==="
  local responses_json
  responses_json="$(RFQ_ID="$rfq_id" list_responses)"
  echo "$responses_json" | pretty_print
  local response_id
  response_id="$(echo "$responses_json" | json_extract "data['data'][0]['id'] if isinstance(data, dict) and 'data' in data and isinstance(data['data'], list) and data['data'] else ''")"
  if [[ -z "$response_id" ]]; then
    echo "Warning: /responses returned no records; falling back to /business/rfq/${rfq_id} detail."
    response_id="$(extract_first_response_id_from_detail "$rfq_id")"
  fi
  if [[ -z "$response_id" ]]; then
    echo "Unable to extract response ID from either responses or detail endpoint."
    exit 1
  fi

  echo ""
  echo "=== RFQ ACCEPT RESPONSE ==="
  RFQ_ID="$rfq_id" RESPONSE_ID="$response_id" accept_response | pretty_print

  echo ""
  echo "=== RFQ DETAIL AFTER ACCEPT ==="
  RFQ_ID="$rfq_id" rfq_detail | pretty_print
}

case "$ACTION" in
  create) create_rfq | pretty_print ;;
  sent) list_sent | pretty_print ;;
  received) list_received | pretty_print ;;
  detail) rfq_detail | pretty_print ;;
  viewed) mark_viewed | pretty_print ;;
  respond) respond_rfq | pretty_print ;;
  responses) list_responses | pretty_print ;;
  accept) accept_response | pretty_print ;;
  reject) reject_response | pretty_print ;;
  smoke) smoke_test ;;
  *)
    echo "Unknown action: $ACTION"
    exit 1
    ;;
esac
